"""One-shot vendoring of Manrope + JetBrains Mono into the repo.

Google already serves each family split by unicode-range, which is exactly the
subsetting we want, so we take those slices rather than running pyftsubset.
Run once; the outputs are committed and the app never talks to Google again.
"""

from __future__ import annotations

import hashlib
import re
import urllib.request
from pathlib import Path

OUT = Path(r"D:\AI-Projects\ai-brain\ai-music-lab\music_lab_ui\static\fonts")
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
WANTED = ("latin", "latin-ext", "cyrillic", "cyrillic-ext")

FAMILIES = {
    "Manrope": {
        "css": "https://fonts.googleapis.com/css2?family=Manrope:wght@400..800&display=block",
        "slug": "manrope",
        "license": "https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/OFL.txt",
    },
    "JetBrains Mono": {
        "css": "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400..700&display=block",
        "slug": "jetbrains-mono",
        "license": "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt",
    },
}

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[a-z-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}",
    re.MULTILINE,
)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []
    manifest: list[str] = []

    for family, spec in FAMILIES.items():
        css = fetch(spec["css"]).decode("utf-8")
        found = 0
        for match in BLOCK.finditer(css):
            subset = match.group("subset")
            if subset not in WANTED:
                continue
            body = match.group("body")
            url = re.search(r"src:\s*url\((?P<u>[^)]+)\)", body).group("u")
            ranges = re.search(r"unicode-range:\s*(?P<r>[^;]+);", body).group("r")
            weight = re.search(r"font-weight:\s*(?P<w>[^;]+);", body)
            weight = weight.group("w").strip() if weight else "400"

            data = fetch(url)
            name = f"{spec['slug']}-{subset}.woff2"
            (OUT / name).write_bytes(data)
            digest = hashlib.sha256(data).hexdigest()
            manifest.append(
                f"| `{name}` | {family} | {subset} | {len(data):,} | `{digest[:16]}…` |"
            )
            faces.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                f"  src: url('/lab-assets/fonts/{name}') format('woff2');\n"
                f"  font-weight: {weight};\n"
                "  font-style: normal;\n"
                "  font-display: block;\n"
                f"  unicode-range: {ranges.strip()};\n"
                "}"
            )
            found += 1
        print(f"{family}: {found} slices")

        licence = fetch(spec["license"]).decode("utf-8")
        (OUT / f"{spec['slug']}-OFL.txt").write_text(licence, encoding="utf-8")

    (OUT / "fonts.css").write_text(
        "/* Generated by scripts/vendor_fonts.py — do not edit by hand.\n"
        "   Served from the app's own /lab-assets mount so the interface never\n"
        "   requests a font from the network. See SOURCE.md. */\n\n"
        + "\n\n".join(faces)
        + "\n",
        encoding="utf-8",
    )
    print("\n".join(manifest))
    total = sum(p.stat().st_size for p in OUT.glob("*.woff2"))
    print(f"total woff2: {total:,} bytes")


if __name__ == "__main__":
    main()
